# Generated by Django 3.2.16 on 2024-05-31 19:42

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deposit', 'Пополнение'), ('withdrawal', 'Списание')], max_length=10, verbose_name='Тип операции')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма транзакции')),
            ],
            options={
                'verbose_name': 'Транзакция сбережения',
                'verbose_name_plural': 'Транзакции сбережений',
            },
        ),
        migrations.CreateModel(
            name='CapitalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Тип капитала')),
            ],
            options={
                'verbose_name': 'Тип капитала',
                'verbose_name_plural': 'Типы капитала',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Валюта')),
                ('symbol', models.CharField(max_length=10, verbose_name='Символ')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('capital_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_type_savings', to='capital.capitaltype', verbose_name='Тип капитала')),
            ],
            options={
                'verbose_name': 'Сбережения',
                'verbose_name_plural': 'Сбережения',
            },
        ),
    ]
