# Generated by Django 3.2.16 on 2024-06-04 12:54

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Капитал',
                'verbose_name_plural': 'Капиталы',
            },
        ),
        migrations.CreateModel(
            name='CapitalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Тип капитала')),
            ],
            options={
                'verbose_name': 'Тип капитала',
                'verbose_name_plural': 'Типы капитала',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Валюта')),
                ('symbol', models.CharField(max_length=10, verbose_name='Символ')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='CapitalsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deposit', 'Пополнение'), ('withdrawal', 'Списание')], max_length=10, verbose_name='Тип операции')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма транзакции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время транзакции')),
                ('capital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='capital.capital', verbose_name='Капитал')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='capital.currency', verbose_name='Валюта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Транзакция сбережения',
                'verbose_name_plural': 'Транзакции сбережений',
            },
        ),
        migrations.AddField(
            model_name='capital',
            name='capital_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitals', to='capital.capitaltype', verbose_name='Тип капитала'),
        ),
        migrations.AddField(
            model_name='capital',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitals', to='capital.currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='capital',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitals', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='capital',
            constraint=models.UniqueConstraint(fields=('user', 'capital_type', 'currency'), name='unique_user_capital_type_currency'),
        ),
    ]
