# Generated by Django 4.2.13 on 2024-05-22 10:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deposit', 'Пополнение'), ('withdrawal', 'Списание')], max_length=10, verbose_name='Тип операции')),
                ('repeat', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно'), ('none', 'Без повтора')], default='none', max_length=10, verbose_name='Повтор операции')),
                ('description', models.TextField(blank=True, help_text='Необязательное поле', null=True, verbose_name='Описание')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма транзакции')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время транзакции')),
            ],
            options={
                'verbose_name': 'Транзакция сбережения',
                'verbose_name_plural': 'Транзакции сбережений',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='CapitalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Тип капитала')),
            ],
            options={
                'verbose_name': 'тип капитала',
                'verbose_name_plural': 'Типы капитала',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Валюта')),
                ('symbol', models.CharField(max_length=10, verbose_name='Символ')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Типы валют',
            },
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Общая сумма')),
                ('capital_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to='capital.capitaltype', verbose_name='Тип')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to='capital.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'вид сбережений пользователя',
                'verbose_name_plural': 'Виды сбережений пользователя',
            },
        ),
    ]
