# Generated by Django 3.2.16 on 2024-05-31 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capital', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_savings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='capitaltype',
            name='currencies',
            field=models.ManyToManyField(related_name='capital_types', to='capital.Currency', verbose_name='Доступные валюты'),
        ),
        migrations.AddField(
            model_name='capitalstransaction',
            name='capital_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_capital_type', to='capital.capitaltype', verbose_name='Тип капитала'),
        ),
        migrations.AddField(
            model_name='capitalstransaction',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capital.currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='capitalstransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
