# Generated by Django 4.2.13 on 2024-05-22 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capital', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capitalstransaction',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capital.currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='capitalstransaction',
            name='savings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_transactions', to='capital.savings', verbose_name='Сбережение'),
        ),
        migrations.AddField(
            model_name='capitalstransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
