# Generated by Django 3.2.16 on 2024-05-31 19:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalstransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 31, 19, 50, 10, 600964, tzinfo=utc), verbose_name='Дата и время транзакции'),
            preserve_default=False,
        ),
    ]
