# Generated by Django 3.2.16 on 2024-06-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0002_auto_20240604_1624'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='capital',
            name='unique_user_capital_type_currency',
        ),
        migrations.AddConstraint(
            model_name='capital',
            constraint=models.UniqueConstraint(fields=('user', 'capital_type', 'currency'), name='Unique user capital type currency'),
        ),
    ]
