# Generated by Django 4.2.13 on 2024-05-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0002_alter_capitaltype_options_alter_savings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitalstransaction',
            name='description',
            field=models.TextField(blank=True, help_text='Необязательное поле', null=True, verbose_name='Описание'),
        ),
    ]
