# Generated by Django 3.2.16 on 2024-05-24 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0003_alter_capitalstransaction_savings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capitalstransaction',
            options={'ordering': ('-created_at',), 'verbose_name': 'Транзакция сбережения', 'verbose_name_plural': 'Транзакции сбережений'},
        ),
        migrations.RenameField(
            model_name='capitalstransaction',
            old_name='pub_date',
            new_name='created_at',
        ),
    ]
