# Generated by Django 3.2.16 on 2024-05-30 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0004_auto_20240524_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitalstransaction',
            name='repeat',
        ),
    ]
