# Generated by Django 3.2.16 on 2024-05-30 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0005_remove_capitalstransaction_repeat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capitalstransaction',
            old_name='type',
            new_name='transaction_type',
        ),
        migrations.AddField(
            model_name='capitalstransaction',
            name='capital_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_capital_type', to='capital.capitaltype', verbose_name='тип сбережения'),
            preserve_default=False,
        ),
    ]
