# Generated by Django 4.2.13 on 2024-05-14 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0005_alter_currency_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savings',
            options={'verbose_name': 'вид сбережений пользователя', 'verbose_name_plural': 'Виды сбережений пользователя'},
        ),
    ]
