# Generated by Django 3.2.16 on 2024-05-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0006_auto_20240530_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitalstransaction',
            name='capital_type',
        ),
        migrations.AlterField(
            model_name='savings',
            name='capital_type',
            field=models.CharField(choices=[('cash', 'наличные'), ('credit funds', 'кредитные средства'), ('bank deposit', 'bank deposit'), ('cryptocurrency', 'криптовалюта'), ('bank account', 'банковский счет')], max_length=20, verbose_name='Тип капитала'),
        ),
        migrations.DeleteModel(
            name='CapitalType',
        ),
    ]
