# Generated by Django 4.2.13 on 2024-05-15 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0006_alter_savings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitalstransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма транзакции'),
        ),
    ]
