# Generated by Django 3.2.16 on 2024-05-31 11:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capital', '0007_auto_20240530_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('capital_type', models.CharField(choices=[('cash', 'наличные'), ('credit funds', 'кредитные средства'), ('bank deposit', 'банковский вклад'), ('cryptocurrency', 'криптовалюта'), ('bank account', 'банковский счёт')], max_length=50, verbose_name='Тип капитала')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_capitals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Капитал пользователя',
                'verbose_name_plural': 'Капиталы пользователя',
            },
        ),
        migrations.CreateModel(
            name='CapitalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Пополнение'), ('withdrawal', 'Списание')], max_length=10, verbose_name='Тип операции')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма транзакции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время транзакции')),
                ('capital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_transactions', to='capital.capital', verbose_name='Капитал')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capital.currency', verbose_name='Валюта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция капитала',
                'verbose_name_plural': 'Транзакции капитала',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserTotalSavings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Общая сумма')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='total_savings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Общая сумма сбережений пользователя',
                'verbose_name_plural': 'Общие суммы сбережений пользователей',
            },
        ),
        migrations.RemoveField(
            model_name='savings',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='savings',
            name='user',
        ),
        migrations.DeleteModel(
            name='CapitalsTransaction',
        ),
        migrations.DeleteModel(
            name='Savings',
        ),
    ]
