# Generated by Django 3.2.16 on 2024-05-31 12:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capital', '0008_auto_20240531_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Пополнение'), ('withdrawal', 'Списание')], max_length=10, verbose_name='Тип операции')),
                ('description', models.TextField(blank=True, help_text='Необязательное поле', null=True, verbose_name='Описание')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма транзакции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время транзакции')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capital.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Транзакция сбережения',
                'verbose_name_plural': 'Транзакции сбережений',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Общая сумма')),
                ('capital_type', models.CharField(choices=[('cash', 'наличные'), ('credit funds', 'кредитные средства'), ('bank deposit', 'bank deposit'), ('cryptocurrency', 'криптовалюта'), ('bank account', 'банковский счет')], max_length=20, verbose_name='Тип капитала')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_currency', to='capital.currency', verbose_name='Валюта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_savings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'вид сбережений пользователя',
                'verbose_name_plural': 'Виды сбережений пользователя',
            },
        ),
        migrations.RemoveField(
            model_name='capitaltransaction',
            name='capital',
        ),
        migrations.RemoveField(
            model_name='capitaltransaction',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='capitaltransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usertotalsavings',
            name='user',
        ),
        migrations.DeleteModel(
            name='Capital',
        ),
        migrations.DeleteModel(
            name='CapitalTransaction',
        ),
        migrations.DeleteModel(
            name='UserTotalSavings',
        ),
        migrations.AddField(
            model_name='capitalstransaction',
            name='savings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_capital_transactions', to='capital.savings', verbose_name='Тип капитала'),
        ),
        migrations.AddField(
            model_name='capitalstransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_capital_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
