# Generated by Django 4.2.13 on 2024-05-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='bio',
            field=models.TextField(blank=True, help_text='Необязательное поле', verbose_name='Биография'),
        ),
    ]
