# Generated by Django 3.2.16 on 2024-05-31 19:42

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Необязательное поле', null=True, verbose_name='Описание')),
                ('goal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Необходимая сумма')),
                ('term', models.PositiveIntegerField(help_text='В месяцах', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Срок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goal_images', verbose_name='Изображение')),
                ('accumulated', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Накоплено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время постановки цели')),
            ],
            options={
                'verbose_name': 'цель',
                'verbose_name_plural': 'Цели',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GoalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deposit', 'Пополнение'), ('withdrawal', 'Списание')], max_length=20, verbose_name='Тип операции')),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма транзакции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время транзакции')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_goal_transactions', to='capital.currency', verbose_name='Валюта')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_transactions', to='goals.goals')),
            ],
            options={
                'verbose_name': 'транзакция для цели',
                'verbose_name_plural': 'Транзакции для цели',
                'ordering': ('-created_at',),
            },
        ),
    ]
