# Generated by Django 4.2.13 on 2024-05-22 10:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Необязательное поле', null=True, verbose_name='Описание')),
                ('goal_amount', models.PositiveIntegerField(verbose_name='Необходимая сумма')),
                ('term', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Срок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goal_images', verbose_name='Изображение')),
                ('currency', models.CharField(max_length=10, verbose_name='Валюта')),
                ('accumulated', models.PositiveIntegerField(default=0, verbose_name='Накоплено')),
                ('is_done', models.BooleanField(default=False, verbose_name='Достигнута ли цель')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время постановки цели')),
            ],
            options={
                'verbose_name': 'цель',
                'verbose_name_plural': 'Цели',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='GoalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deposit', 'Пополнение'), ('withdrawal', 'Списание')], max_length=20, verbose_name='Тип операции')),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма транзакции')),
                ('repeat', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно'), ('none', 'Без повтора')], default='none', max_length=20, verbose_name='Повтор операции')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время транзакции')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_transactions', to='goals.goals')),
            ],
            options={
                'verbose_name': 'транзакция для цели',
                'verbose_name_plural': 'Транзакции для цели',
                'ordering': ('-pub_date',),
            },
        ),
    ]
