# Generated by Django 4.2.13 on 2024-05-14 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goals',
            options={'verbose_name': 'цель', 'verbose_name_plural': 'Цели'},
        ),
        migrations.AlterModelOptions(
            name='goaltransaction',
            options={'verbose_name': 'транзакция для цели', 'verbose_name_plural': 'Транзакции для цели'},
        ),
    ]
