# Generated by Django 4.2.13 on 2024-05-22 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0003_alter_capitalstransaction_savings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goaltransaction',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='currency_goal_transactions', to='capital.currency', verbose_name='Валюта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goals',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_goals', to='capital.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='goals',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='goaltransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_goal_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
