# Generated by Django 4.2.13 on 2024-05-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_alter_goals_options_alter_goaltransaction_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goals',
            old_name='goal_sum',
            new_name='goal_amount',
        ),
        migrations.AlterField(
            model_name='goals',
            name='description',
            field=models.TextField(blank=True, help_text='Необязательное поле', null=True, verbose_name='Описание'),
        ),
    ]
