# Generated by Django 4.2.13 on 2024-05-14 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_rename_goal_sum_goals_goal_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goaltransaction',
            name='transaction_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма транзакции'),
            preserve_default=False,
        ),
    ]
