# Generated by Django 3.2.16 on 2024-05-24 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_goaltransaction_currency_alter_goals_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goals',
            options={'ordering': ('-created_at',), 'verbose_name': 'цель', 'verbose_name_plural': 'Цели'},
        ),
        migrations.AlterModelOptions(
            name='goaltransaction',
            options={'ordering': ('-created_at',), 'verbose_name': 'транзакция для цели', 'verbose_name_plural': 'Транзакции для цели'},
        ),
        migrations.RenameField(
            model_name='goals',
            old_name='pub_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='goaltransaction',
            old_name='pub_date',
            new_name='created_at',
        ),
    ]
