# Generated by Django 3.2.16 on 2024-05-27 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_auto_20240524_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='term',
            field=models.PositiveIntegerField(help_text='В месяцах', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Срок'),
        ),
    ]
