# Generated by Django 3.2.16 on 2024-05-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_alter_goals_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='accumulated',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
