# Generated by Django 3.2.16 on 2024-05-28 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_goals_last_repeat_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goals',
            name='last_repeat_choice',
        ),
        migrations.RemoveField(
            model_name='goaltransaction',
            name='repeat',
        ),
    ]
