# Generated by Django 3.2.16 on 2024-05-28 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0009_auto_20240528_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goals',
            name='is_done',
        ),
    ]
